# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'Eve' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'CVCalendarKit', '~> 0.1.1'

end

target 'EveTests' do

end
